In [1]:
import sys
import os
sys.path.append("..")

In [2]:
import pickle
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [3]:
from src.data_preprocessing import LoanDataPreprocessor
from src.feature_engineering import apply_feature_engineering

In [4]:
print(os.getcwd())

d:\PD_MODEL\Models

In [6]:
with open('D:\PD_MODEL\PARAMS\pd_model.pkl','rb') as f:
    model=pickle.load(f)

with open('D:\PD_MODEL\PARAMS\woe_binner.pkl', 'rb') as f:
    woe=pickle.load(f)

with open(r'D:\PD_MODEL\PARAMS\final_features.pkl', 'rb') as f:
    final_features=pickle.load(f)

In [7]:
data_processor=LoanDataPreprocessor()

INFO:root:Preprocessing version: v1.0

In [8]:
df_dev=data_processor.preprocess('D:\PD_MODEL\DATA\loan_data_2007_2014.csv')

INFO:root:Cleaning employment length
INFO:root:Cleaning term
INFO:root:dates conversion
WARNING:root:29 missing earliest_cr_line_date fill with issue_d
INFO:root:credit age creation
INFO:root:missing values handling
INFO:root:target variable creation
INFO:root:Applying outlier capping on 33 columns
INFO:root:final dataset shape: (466285, 81)

In [9]:
df_dev_fe,feature_cols=apply_feature_engineering(df_dev, None)

INFO:root:Starting feature engineering
INFO:root:Applying categorical grouping
INFO:root:Feature engineering completed. Shape: (466285, 86)
INFO:root:Feature engineering version: v1.0

In [10]:
df_dev_fe,feature_cols=apply_feature_engineering(df_dev, None)

INFO:root:Starting feature engineering
INFO:root:Applying categorical grouping
INFO:root:Feature engineering completed. Shape: (466285, 86)
INFO:root:Feature engineering version: v1.0

In [12]:
df_dev_woe=woe.apply_bins(df_dev_fe)

In [13]:
df_dev_woe=woe.transform(df_dev_woe)

In [14]:
final_features

['grade_woe',
 'inq_last_6mths_bin_woe',
 'annual_inc_bin_woe',
 'purpose_woe',
 'credit_age_months_bin_woe',
 'dti_bin_woe',
 'initial_list_status_woe',
 'home_ownership_woe',
 'verification_status_woe']

In [15]:
df_dev_woe=df_dev_woe[final_features]

In [16]:
X_dev=sm.add_constant(df_dev_woe)
X_dev=X_dev[['const']+final_features]
df_dev_woe['pd']=model.predict_proba(X_dev)

INFO:root:Generating predictions
INFO:root:scoring data shape : (466285, 10)

In [17]:
df_dev=df_dev_woe

In [18]:
df_oot=data_processor.preprocess('D:\PD_MODEL\DATA\loan_data_2015.csv')

INFO:root:Cleaning employment length
INFO:root:Cleaning term
INFO:root:dates conversion
INFO:root:credit age creation
INFO:root:missing values handling
INFO:root:target variable creation
INFO:root:Applying outlier capping on 47 columns
INFO:root:final dataset shape: (421094, 80)

In [19]:
df_oot.shape

(421094, 80)

In [20]:

pd.options.display.max_rows=None

In [21]:
df_oot.isnull().sum()

id                             0
member_id                      0
loan_amnt                      0
funded_amnt                    0
funded_amnt_inv                0
term                           0
int_rate                       0
installment                    0
grade                          0
sub_grade                      0
emp_title                      0
emp_length                     0
home_ownership                 0
annual_inc                     0
verification_status            0
issue_d                        0
loan_status                    0
pymnt_plan                     0
url                            0
desc                           0
purpose                        0
title                          0
zip_code                       0
addr_state                     0
dti                            0
delinq_2yrs                    0
earliest_cr_line               0
inq_last_6mths                 0
mths_since_last_delinq         0
mths_since_last_record         0
open_acc                       0
pub_rec                        0
revol_bal                      0
revol_util                     0
total_acc                      0
initial_list_status            0
out_prncp                      0
out_prncp_inv                  0
total_pymnt                    0
total_pymnt_inv                0
total_rec_prncp                0
total_rec_int                  0
total_rec_late_fee             0
recoveries                     0
collection_recovery_fee        0
last_pymnt_d                   0
last_pymnt_amnt                0
next_pymnt_d                   0
last_credit_pull_d             0
collections_12_mths_ex_med     0
mths_since_last_major_derog    0
policy_code                    0
application_type               0
annual_inc_joint               0
dti_joint                      0
verification_status_joint      0
acc_now_delinq                 0
tot_coll_amt                   0
tot_cur_bal                    0
open_acc_6m                    0
open_il_6m                     0
open_il_12m                    0
open_il_24m                    0
mths_since_rcnt_il             0
total_bal_il                   0
il_util                        0
open_rv_12m                    0
open_rv_24m                    0
max_bal_bc                     0
all_util                       0
total_rev_hi_lim               0
inq_fi                         0
total_cu_tl                    0
inq_last_12m                   0
emp_length_int                 0
term_int                       0
earliest_cr_line_date          0
credit_age_months              0
loan_status_clean              0
good_bad                       0
dtype: int64

In [22]:
df_oot_fe, feature_cols=apply_feature_engineering(df_oot, None)

INFO:root:Starting feature engineering
INFO:root:Applying categorical grouping
INFO:root:Feature engineering completed. Shape: (421094, 85)
INFO:root:Feature engineering version: v1.0

In [23]:
df_oot_fe.shape

(421094, 85)

In [24]:
print(df_oot_fe.columns)

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'term_int', 'earliest_cr_line_date',
       'credit_age_months', 'loan_status_clean', 'good_bad',
       'home_ownership_grp', 'purpose_grp', 'addr_state_grp',
       'mths_since_last_delinq_missing', 'mths_since_last_record_missing'],
      dtype='object')

In [25]:
df_oot_fe.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,term_int,earliest_cr_line_date,credit_age_months,loan_status_clean,good_bad,home_ownership_grp,purpose_grp,addr_state_grp,mths_since_last_delinq_missing,mths_since_last_record_missing
0,60516983,64537751,20000,20000,20000,36 months,12.29,667.06,C,C1,...,36,2000-09-01,182,Charged Off,1,OWN,medium_risk,MEDIUM_RISK,0,0
1,60187139,64163931,11000,11000,11000,36 months,12.69,369.00,C,C2,...,36,2002-09-01,158,Charged Off,1,MORTGAGE,medium_risk,MEDIUM_RISK,0,0
2,60356453,64333218,7000,7000,7000,36 months,9.99,225.84,B,B3,...,36,2006-02-01,116,Charged Off,1,MORTGAGE,medium_risk,HIGH_RISK,0,0
3,59955769,63900496,10000,10000,10000,36 months,10.99,327.34,B,B4,...,36,1999-10-01,193,Charged Off,1,MORTGAGE,low_risk,MEDIUM_RISK,0,0
4,58703693,62544456,9550,9550,9550,36 months,19.99,354.87,E,E4,...,36,1999-11-01,192,Charged Off,1,RENT,medium_risk,MEDIUM_RISK,0,0

In [26]:
df_oot_woe=woe.apply_bins(df_oot_fe)
df_oot_woe=woe.transform(df_oot_woe)
df_oot_woe.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,initial_list_status_woe,int_rate_bin_woe,dti_bin_woe,annual_inc_bin_woe,installment_bin_woe,delinq_2yrs_bin_woe,inq_last_6mths_bin_woe,credit_age_months_bin_woe,open_acc_bin_woe,total_acc_bin_woe
0,60516983,64537751,20000,20000,20000,36 months,12.29,667.06,C,C1,...,0.223494,0.385109,-0.090694,0.022372,-0.036421,-0.000472,-0.062870,0.018155,0.043296,0.087128
1,60187139,64163931,11000,11000,11000,36 months,12.69,369.00,C,C2,...,0.223494,0.385109,-0.203865,-0.197276,-0.002328,-0.000472,0.195875,-0.107848,-0.003823,0.087128
2,60356453,64333218,7000,7000,7000,36 months,9.99,225.84,B,B3,...,-0.105930,1.052007,-0.203865,-0.197276,0.086846,-0.000472,-0.062870,-0.213277,0.043296,0.087128
3,59955769,63900496,10000,10000,10000,36 months,10.99,327.34,B,B4,...,-0.105930,0.385109,-0.203865,-0.197276,-0.002328,-0.000472,-0.297868,0.018155,0.043296,0.087128
4,58703693,62544456,9550,9550,9550,36 months,19.99,354.87,E,E4,...,0.223494,-0.462954,-0.203865,-0.197276,-0.002328,-0.000472,-0.297868,0.018155,-0.005804,0.033141

In [27]:
final_features

['grade_woe',
 'inq_last_6mths_bin_woe',
 'annual_inc_bin_woe',
 'purpose_woe',
 'credit_age_months_bin_woe',
 'dti_bin_woe',
 'initial_list_status_woe',
 'home_ownership_woe',
 'verification_status_woe']

In [28]:
X_oot=df_oot_woe[final_features].copy()

In [29]:
X_oot=sm.add_constant(X_oot)

In [30]:
X_oot=X_oot[['const']+final_features]

In [31]:
df_oot_woe['pd']=model.predict_proba(X_oot)

INFO:root:Generating predictions
INFO:root:scoring data shape : (421094, 10)

In [32]:
df_oot_woe=df_oot_woe[final_features+ ['pd']]

In [33]:
df_oot_woe.head()

,grade_woe,inq_last_6mths_bin_woe,annual_inc_bin_woe,purpose_woe,credit_age_months_bin_woe,dti_bin_woe,initial_list_status_woe,home_ownership_woe,verification_status_woe,pd
0,-0.056491,-0.062870,0.022372,-0.043086,0.018155,-0.090694,0.223494,0.020963,0.053403,0.098052
1,-0.056491,0.195875,-0.197276,-0.043086,-0.107848,-0.203865,0.223494,0.146051,0.053403,0.104882
2,0.373511,-0.062870,-0.197276,-0.043086,-0.213277,-0.203865,-0.105930,0.146051,0.053403,0.119475
3,0.373511,-0.297868,-0.197276,0.274140,0.018155,-0.203865,-0.105930,0.146051,0.053403,0.105979
4,-0.675120,-0.297868,-0.197276,-0.043086,0.018155,-0.203865,0.223494,-0.165189,-0.175220,0.245883

In [34]:
def calculate_psi(expected, actual, bins=10):

    # CASE 1: DISCRETE / LOW UNIQUE
    if expected.dtype == 'object' or expected.nunique() < bins:

        all_vals = sorted(set(expected.unique()).union(set(actual.unique())))

        expected_dist = expected.value_counts(normalize=True).reindex(all_vals, fill_value=0)
        actual_dist   = actual.value_counts(normalize=True).reindex(all_vals, fill_value=0)

        psi_df = pd.DataFrame({
            'expected': expected_dist,
            'actual': actual_dist
        })

    else:
        # CASE 2: CONTINUOUS
        expected_bins = pd.qcut(expected, q=bins, duplicates='drop')
        actual_bins = pd.cut(actual, bins=expected_bins.cat.categories)

        expected_dist = expected_bins.value_counts(normalize=True).sort_index()
        actual_dist   = actual_bins.value_counts(normalize=True).sort_index()

        psi_df = pd.DataFrame({
            'expected': expected_dist,
            'actual': actual_dist
        }).fillna(0)

    # Avoid zeros
    psi_df['expected'] = psi_df['expected'].replace(0, 1e-6)
    psi_df['actual']   = psi_df['actual'].replace(0, 1e-6)

    # PSI formula
    psi_df['psi'] = (psi_df['expected'] - psi_df['actual']) * \
                    np.log(psi_df['expected'] / psi_df['actual'])

    return psi_df, psi_df['psi'].sum()

In [35]:
#score PSI
psi_table, score_psi=calculate_psi(df_dev['pd'],df_oot_woe['pd'])

In [36]:
psi_table

                                expected    actual       psi
pd
(0.012899999999999998, 0.0391]  0.100001  0.156723  0.025485
(0.0391, 0.0557]                0.100001  0.113070  0.001605
(0.0557, 0.0704]                0.100010  0.111571  0.001265
(0.0704, 0.0841]                0.099999  0.105672  0.000313
(0.0841, 0.098]                 0.099992  0.092186  0.000635
(0.098, 0.113]                  0.099999  0.085855  0.002157
(0.113, 0.132]                  0.100014  0.089412  0.001188
(0.132, 0.156]                  0.099997  0.083618  0.002930
(0.156, 0.194]                  0.099986  0.084314  0.002672
(0.194, 0.612]                  0.100001  0.077579  0.005693

In [37]:
score_psi

np.float64(0.043941813576220366)

In [38]:
feature_cols = final_features

for col in feature_cols:

    missing_in_oot = set(df_dev[col].unique()) - set(df_oot_woe[col].unique())
    missing_in_dev = set(df_oot_woe[col].unique()) - set(df_dev[col].unique())

    if missing_in_oot or missing_in_dev:

        print(f"{col} shows population distribution differences between DEV and OOT datasets.")

        if missing_in_oot:
            print("Categories present in DEV but absent in OOT:", missing_in_oot)

        if missing_in_dev:
            print("Categories present in OOT but absent in DEV:", missing_in_dev)

        print("-" * 80)

credit_age_months_bin_woe shows population distribution differences between DEV and OOT datasets.
Categories present in DEV but absent in OOT: {np.float64(0.0)}
--------------------------------------------------------------------------------
home_ownership_woe shows population distribution differences between DEV and OOT datasets.
Categories present in DEV but absent in OOT: {np.float64(-0.8561419809643181), np.float64(-0.3723450295862467)}
--------------------------------------------------------------------------------

In [39]:
feature_psi={}
feature_cols=final_features

for col in feature_cols:
    expected=df_dev[col]
    actual=df_oot_woe[col]

         
    _, psi_val=calculate_psi(expected, actual)
    feature_psi[col]=psi_val

feature_psi_df=pd.DataFrame.from_dict(feature_psi, orient='index', columns=['PSI']).sort_values(by='PSI', ascending=False)
feature_psi_df

                                PSI
purpose_woe                3.130525
initial_list_status_woe    0.333003
inq_last_6mths_bin_woe     0.053415
verification_status_woe    0.048312
dti_bin_woe                0.043434
credit_age_months_bin_woe  0.013183
home_ownership_woe         0.006986
grade_woe                  0.006735
annual_inc_bin_woe         0.005028

In [40]:
def psi_alert_label(psi):
    if psi <0.1:
        return 'Stable'
    elif psi <0.25:
        return 'Moderate shift'
    else:
        return 'Significant Drift'

In [41]:
feature_psi_df['alert']=feature_psi_df['PSI'].apply(psi_alert_label)

In [42]:
def monitoring_action(psi):
    if psi<0.1:
        return 'No action'
    elif psi <0.25:
        return 'Monitor'
    else:
        return 'Investigate'

In [43]:
feature_psi_df['action']=feature_psi_df['PSI'].apply(monitoring_action)

In [44]:
feature_psi_df

                                PSI              alert       action
purpose_woe                3.130525  Significant Drift  Investigate
initial_list_status_woe    0.333003  Significant Drift  Investigate
inq_last_6mths_bin_woe     0.053415             Stable    No action
verification_status_woe    0.048312             Stable    No action
dti_bin_woe                0.043434             Stable    No action
credit_age_months_bin_woe  0.013183             Stable    No action
home_ownership_woe         0.006986             Stable    No action
grade_woe                  0.006735             Stable    No action
annual_inc_bin_woe         0.005028             Stable    No action

In [45]:
top_drift=feature_psi_df[feature_psi_df['PSI']>0.25]
print(top_drift)

                              PSI              alert       action
purpose_woe              3.130525  Significant Drift  Investigate
initial_list_status_woe  0.333003  Significant Drift  Investigate

In [46]:
summary=feature_psi_df['alert'].value_counts()
print(summary)

alert
Stable               7
Significant Drift    2
Name: count, dtype: int64

In [48]:
feature_psi_df.to_csv(r'D:\PD_MODEL\DATA\feature_psi.csv')

In [49]:
score_alert=psi_alert_label(score_psi)
score_action=monitoring_action(score_psi)
print(f'score alert:{score_alert} and action:{score_action}')

score alert:Stable and action:No action

In [50]:
model_version="V1.0"
monitoring_date=pd.Timestamp.today()
monitoring_date

Timestamp('2026-06-07 21:28:49.946290')